// Auto-generated by mujoco-react. Do not edit.
// Regenerate by running Vite with the mujocoReact() plugin or `mujoco-react codegen`.

import { registerModelResources } from 'mujoco-react';
import type { ModelResource } from 'mujoco-react';

type GeneratedModelResources = {
  readonly so101: {
    readonly actuators: {
      readonly elbow_flex: 'elbow_flex';
      readonly gripper: 'gripper';
      readonly shoulder_lift: 'shoulder_lift';
      readonly shoulder_pan: 'shoulder_pan';
      readonly wrist_flex: 'wrist_flex';
      readonly wrist_roll: 'wrist_roll';
    };
    readonly sensors: {};
    readonly bodies: {
      readonly base: 'base';
      readonly camera_mount: 'camera_mount';
      readonly gripper: 'gripper';
      readonly lower_arm: 'lower_arm';
      readonly moving_jaw_so101_v1: 'moving_jaw_so101_v1';
      readonly shoulder: 'shoulder';
      readonly upper_arm: 'upper_arm';
      readonly wrist: 'wrist';
    };
    readonly joints: {
      readonly elbow_flex: 'elbow_flex';
      readonly gripper: 'gripper';
      readonly shoulder_lift: 'shoulder_lift';
      readonly shoulder_pan: 'shoulder_pan';
      readonly wrist_flex: 'wrist_flex';
      readonly wrist_roll: 'wrist_roll';
    };
    readonly sites: {
      readonly baseframe: 'baseframe';
      readonly gripperframe: 'gripperframe';
    };
    readonly geoms: {
      readonly camera_box1: 'camera_box1';
      readonly camera_box2: 'camera_box2';
      readonly fixed_jaw_box1: 'fixed_jaw_box1';
      readonly fixed_jaw_box2: 'fixed_jaw_box2';
      readonly fixed_jaw_box3: 'fixed_jaw_box3';
      readonly fixed_jaw_box4: 'fixed_jaw_box4';
      readonly fixed_jaw_box5: 'fixed_jaw_box5';
      readonly fixed_jaw_box6: 'fixed_jaw_box6';
      readonly fixed_jaw_box7: 'fixed_jaw_box7';
      readonly fixed_jaw_sph_tip1: 'fixed_jaw_sph_tip1';
      readonly fixed_jaw_sph_tip2: 'fixed_jaw_sph_tip2';
      readonly fixed_jaw_sph_tip3: 'fixed_jaw_sph_tip3';
      readonly moving_jaw_box1: 'moving_jaw_box1';
      readonly moving_jaw_box2: 'moving_jaw_box2';
      readonly moving_jaw_box3: 'moving_jaw_box3';
      readonly moving_jaw_sph_tip1: 'moving_jaw_sph_tip1';
      readonly moving_jaw_sph_tip2: 'moving_jaw_sph_tip2';
      readonly moving_jaw_sph_tip3: 'moving_jaw_sph_tip3';
    };
    readonly keyframes: {};
    readonly cameras: {
      readonly wrist_cam: 'wrist_cam';
    };
  };
};

const generatedModelResources: GeneratedModelResources = {
  so101: {
    actuators: {
      elbow_flex: 'elbow_flex',
      gripper: 'gripper',
      shoulder_lift: 'shoulder_lift',
      shoulder_pan: 'shoulder_pan',
      wrist_flex: 'wrist_flex',
      wrist_roll: 'wrist_roll',
    },
    sensors: {},
    bodies: {
      base: 'base',
      camera_mount: 'camera_mount',
      gripper: 'gripper',
      lower_arm: 'lower_arm',
      moving_jaw_so101_v1: 'moving_jaw_so101_v1',
      shoulder: 'shoulder',
      upper_arm: 'upper_arm',
      wrist: 'wrist',
    },
    joints: {
      elbow_flex: 'elbow_flex',
      gripper: 'gripper',
      shoulder_lift: 'shoulder_lift',
      shoulder_pan: 'shoulder_pan',
      wrist_flex: 'wrist_flex',
      wrist_roll: 'wrist_roll',
    },
    sites: {
      baseframe: 'baseframe',
      gripperframe: 'gripperframe',
    },
    geoms: {
      camera_box1: 'camera_box1',
      camera_box2: 'camera_box2',
      fixed_jaw_box1: 'fixed_jaw_box1',
      fixed_jaw_box2: 'fixed_jaw_box2',
      fixed_jaw_box3: 'fixed_jaw_box3',
      fixed_jaw_box4: 'fixed_jaw_box4',
      fixed_jaw_box5: 'fixed_jaw_box5',
      fixed_jaw_box6: 'fixed_jaw_box6',
      fixed_jaw_box7: 'fixed_jaw_box7',
      fixed_jaw_sph_tip1: 'fixed_jaw_sph_tip1',
      fixed_jaw_sph_tip2: 'fixed_jaw_sph_tip2',
      fixed_jaw_sph_tip3: 'fixed_jaw_sph_tip3',
      moving_jaw_box1: 'moving_jaw_box1',
      moving_jaw_box2: 'moving_jaw_box2',
      moving_jaw_box3: 'moving_jaw_box3',
      moving_jaw_sph_tip1: 'moving_jaw_sph_tip1',
      moving_jaw_sph_tip2: 'moving_jaw_sph_tip2',
      moving_jaw_sph_tip3: 'moving_jaw_sph_tip3',
    },
    keyframes: {},
    cameras: {
      wrist_cam: 'wrist_cam',
    },
  },
};

registerModelResources(generatedModelResources);

declare module 'mujoco-react' {
  interface Register {
    models: {
      so101: {
        actuators: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
        sensors: never;
        bodies: 'base' | 'camera_mount' | 'gripper' | 'lower_arm' | 'moving_jaw_so101_v1' | 'shoulder' | 'upper_arm' | 'wrist';
        joints: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
        sites: 'baseframe' | 'gripperframe';
        geoms: 'camera_box1' | 'camera_box2' | 'fixed_jaw_box1' | 'fixed_jaw_box2' | 'fixed_jaw_box3' | 'fixed_jaw_box4' | 'fixed_jaw_box5' | 'fixed_jaw_box6' | 'fixed_jaw_box7' | 'fixed_jaw_sph_tip1' | 'fixed_jaw_sph_tip2' | 'fixed_jaw_sph_tip3' | 'moving_jaw_box1' | 'moving_jaw_box2' | 'moving_jaw_box3' | 'moving_jaw_sph_tip1' | 'moving_jaw_sph_tip2' | 'moving_jaw_sph_tip3';
        keyframes: never;
        cameras: 'wrist_cam';
      };
    };
    actuators: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
    bodies: 'base' | 'camera_mount' | 'gripper' | 'lower_arm' | 'moving_jaw_so101_v1' | 'shoulder' | 'upper_arm' | 'wrist';
    joints: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
    sites: 'baseframe' | 'gripperframe';
    geoms: 'camera_box1' | 'camera_box2' | 'fixed_jaw_box1' | 'fixed_jaw_box2' | 'fixed_jaw_box3' | 'fixed_jaw_box4' | 'fixed_jaw_box5' | 'fixed_jaw_box6' | 'fixed_jaw_box7' | 'fixed_jaw_sph_tip1' | 'fixed_jaw_sph_tip2' | 'fixed_jaw_sph_tip3' | 'moving_jaw_box1' | 'moving_jaw_box2' | 'moving_jaw_box3' | 'moving_jaw_sph_tip1' | 'moving_jaw_sph_tip2' | 'moving_jaw_sph_tip3';
    cameras: 'wrist_cam';
  }

  export namespace ModelActuators {
    export type so101 = ModelResource<'so101', 'actuators'>;
  }

  export namespace ModelSensors {
    export type so101 = ModelResource<'so101', 'sensors'>;
  }

  export namespace ModelBodies {
    export type so101 = ModelResource<'so101', 'bodies'>;
  }

  export namespace ModelJoints {
    export type so101 = ModelResource<'so101', 'joints'>;
  }

  export namespace ModelSites {
    export type so101 = ModelResource<'so101', 'sites'>;
  }

  export namespace ModelGeoms {
    export type so101 = ModelResource<'so101', 'geoms'>;
  }

  export namespace ModelKeyframes {
    export type so101 = ModelResource<'so101', 'keyframes'>;
  }

  export namespace ModelCameras {
    export type so101 = ModelResource<'so101', 'cameras'>;
  }

}
